const checks = [
  ['validate:all-portfolios', ['scripts/validate-portfolio.js', 'portfolio/etf/portfolio.md', 'portfolio/_template/portfolio.md']],
  ['validate:strategy', ['scripts/validate-strategy.js', 'portfolio/etf/portfolio.md']],
  ['check:activation', ['scripts/check-portfolio-activation.js', 'portfolio/etf/portfolio.md']],
  ['check:generated-state', ['scripts/check-generated-state.js', 'portfolio/etf']],
  ['check:safety', ['scripts/check-safety-controls.js', 'portfolio/etf']],
  ['verify:execution', ['scripts/verify-execution-surface.js']],
  ['test:reporting-completeness', ['scripts/test-reporting-completeness.js']],
  ['test:structured-summary-artifacts', ['scripts/test-structured-summary-artifacts.js']],
  ['test:multi-portfolio-overview', ['scripts/test-multi-portfolio-overview.js']],
  ['test:dashboard-command-center', ['scripts/test-dashboard-command-center.js']],
  ['test:trade-cli-surface', ['scripts/test-trade-cli-surface.js']],
  ['test:execution-authority', ['scripts/test-execution-authority.js']],
  ['test:effective-config', ['scripts/test-effective-config.js']],
  ['test:delivery-posture', ['scripts/test-delivery-posture.js']],
  ['test:execution-command-surface-doc', ['scripts/test-execution-command-surface-doc.js']],
  ['test:system-policy-contract', ['scripts/test-system-policy-contract.js']],
  ['test:artifact-policy-contract', ['scripts/test-artifact-policy-contract.js']],
  ['test:operator-incident-summary', ['scripts/test-operator-incident-summary.js']],
  ['test:operator-runbooks-contract', ['scripts/test-operator-runbooks-contract.js']],
  ['test:observability-doc-contract', ['scripts/test-observability-doc-contract.js']],
  ['test:trading-workflow-doc-contract', ['scripts/test-trading-workflow-doc-contract.js']],
  ['test:transmitted-live-operations-doc-contract', ['scripts/test-transmitted-live-operations-doc-contract.js']],
  ['test:market-calendar-readiness', ['scripts/test-market-calendar-readiness.js']],
  ['test:market-calendar-artifact-has-holiday-fields', ['scripts/test-market-calendar-artifact-has-holiday-fields.js']],
  ['test:diagnostics-require-paths', ['scripts/test-diagnostics-require-paths.js']],
  ['test:approved-instruments-sentinel-identity', ['scripts/test-approved-instruments-sentinel-identity.js']],
  ['test:cancel-broker-only-orderid', ['scripts/test-cancel-broker-only-orderid.js']],
  ['test:clear-circuit-breaker-audit', ['scripts/test-clear-circuit-breaker-audit.js']],
  ['test:cron-job-policy', ['scripts/test-cron-job-policy.js']],
  ['test:repo-root-cleanliness', ['scripts/test-repo-root-cleanliness.js']],
  ['test:soak-baseline-shape', ['scripts/test-soak-baseline-shape.js']],
  ['test:market-hours', ['tests/test-marketHours.js']],
  ['test:ibkr-readiness', ['tests/test-ibkr-readiness.js']],
];

module.exports = { checks };
