const checks = [
  'test-portfolio-execution-gates.js',
  'test-trade-state-reconciliation.js',
  'test-order-status-not-found-reconciliation.js',
  'test-runtime-broker-error-state.js',
  'test-interactive-brokers-filled-order-surface.js',
  'test-interactive-brokers-completed-order-surface.js',
  'test-portfolio-order-lifecycle-e2e.js',
  'test-partial-fill-status-inference.js',
  'test-history-snapshot-types.js',
  'test-dashboard-execution-summary.js',
  'test-latest-trade-proposals-dedup.js',
  'test-duplicate-submission-guard.js',
  'test-approval-transition-guard.js',
  'test-stale-proposal-approval-guard.js',
  'test-reject-trade-transition.js',
  'test-open-order-row-list.js',
  'test-resync-idempotent-open-order-filter.js',
  'test-resync-latest-row-only.js',
  'test-first-purchase-sales-approval-gates.js',
  'test-trade-blocking-safety-hardening.js',
  'test-stage-live-order-records-broker-order-id.js',
  'test-cancel-staged-order-reconciliation.js',
  'test-cancel-runtime-error-state.js',
  'test-staged-order-approval-guard.js',
  'test-writable-execution-handoff-e2e.js',
  'test-writable-live-lane-acceptance.js',
  'test-transmitted-live-lane-acceptance.js',
  'test-operator-action-audit-trail.js',
  'test-history-material-events.js',
  'test-transmitted-live-gating.js',
  'test-transmitted-live-submission-surface.js',
  'test-risk-observability.js',
];

module.exports = { checks };
